version: "3.7" 
services:
  mynet8:
    container_name: mynet8
    image: tiennsloit/net8:1.0.2
    build:
      context: .    
      target: debug
    volumes:
      - ./HelloWorldRazor/:/work/
    ports:
      - 5001:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080